name: Setup development environment
description: Setup mise and install dependencies

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2.2.3

    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}

    - run: bun install --frozen-lockfile
      shell: bash
