name: Setup development environment
description: Setup mise and install dependencies

inputs:
  cache_save:
    description: Whether to save mise cache (set to false in parallel jobs to avoid conflicts)
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2.2.3
      with:
        cache_save: ${{ inputs.cache_save }}

    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}

    - run: bun install --frozen-lockfile
      shell: bash
